language: java
jdk: openjdk8
cache:
    directories:
     - $HOME/.m2
     - node_installation
branches:
  only:
  - master
git:
  depth: 3
script:
  - mvn test -B
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key:
    secure: "iHH/4pDDH9iN6cx8Ow3SNmB7uE+LR5FDl30fR0b66IidDB2GB8g0cPU9BxhLJ2G6ICcg8/g3GEFgR7W0x178ICVfaR7T5WD1DCsg52XmxFloD/nmifiUuHCMPsWtYbKYUeYfnt/AqrPK5rnPignxqwekc7fW/Gsb1WqBzBopmPr7szMVBxILBdbmwzXqlYYc5c8UJ8wZvfJ9OToaFBTm+z2kbqWPAiSNTSd2LsN8UdWKxZRO9708cZ/XjG1Kn70MDEEbsEnhtUpJHPGjzS/FDCkopG37+/M6tXCY3LWjK1rBagWeAv6zEglfUpV4eVtIv9639gxsjjIH0MEbg8W/moBvvXIsRieAFCpNp0GIbzgNqv2DY0XgyMEeaNuldL7pPncR+oExtfQ3UGNT3UC9qL2oK26bWiyP9xzDokBH6XfNcVLOlb+L4vqNB2mCVHlXBekEoNoHJ9O+5qwnA2gPWN5kZRDxihcMwLCr9zLOPLYIFoT8VGLQb0dh+JlymsXfFV77v06RzuS+IfPwYeslHA6F4o9jPI+AL9Y8VUBsUyGT2fy5fBTEhajOfOyx6vS+f3yn6H+BQpvhWj0CyAHGD4ZwnVIj29/NAit6K9XJk1IcIGFvFRzb8zHwLlFqNeUuBUl2XcOCbg9eRoIYF6TBtbRp5AEPWxN5WaE6JHAR4Kw="  
  app: bono-corporativo
  on:
    repo: finanza-02/bono-corporativo